jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python script
        run: python test.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: output.txt

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: output-file

      - name: Read artifact
        run: cat output.txt
