name: Example Workflow

on: [push]  # 触发条件：代码 push 时运行

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Python script
        run: python test.py

      - name: Use the output
        run: echo "The result is $RESULT"
