name: Update Baidu Content

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update_baidu_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      #不做判断获取直接保存
      # - name: Visit Baidu and save content
      #   run: |
      #     echo ${{ secrets.u_value }} 
      #     curl -L -k ${{ secrets.u_value }}  > .devcontainer/docs/v.txt
      #     cat .devcontainer/docs/v.txt
      #     echo '::set-output name=v::$(cat .devcontainer/docs/v.txt)'
      #     echo $(date) > last_updated.txt
      
      #原始输出
      # echo '::set-output name=v::$(cat .devcontainer/docs/v.txt)'
      - name: Visit Baidu and save content
        run: |
          vmes_content=$(curl -L -k ${{ secrets.u_value }})
          if echo "$vmes_content" | grep -q -e "https" -e "error"; then
            echo "Content contains 'sensitive', skipping saving"
          else
            echo "$vmes_content" > .devcontainer/docs/v.txt
            cat .devcontainer/docs/v.txt
            echo 'v=$(cat .devcontainer/docs/v.txt)' >> $GITHUB_STATE
       
          fi
          echo $(date) > last_updated.txt
      
      - name: Commit changes
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git add .devcontainer/docs/v.txt last_updated.txt
          git commit -m "Update Baidu content"
          git push

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
