name: Update Baidu Content

on:
  schedule:
    - cron: '0 */6 * * *' # 每天 UTC 00:00 执行
  workflow_dispatch:

jobs:
  update_baidu_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Visit Baidu and save content
        run: |
          curl -L -k https://suo.yt/fQ57S2j > v.txt
          cat v.txt
          echo '::set-output name=v::$(cat v.txt)'
          echo $(date) > last_updated.txt
      
      - name: Commit changes
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git add v.txt last_updated.txt
          git commit -m "Update Baidu content"
          git push

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
